exports.showSign2=function(req,res){
res.send('我是登录页面2')
}
exports.showSign3=function(req,res){
res.send('我是登录页面3')
}
exports.showSign4=function(req,res){
res.send('我是登录页面4')
}
exports.showSign5=function(req,res){
res.send('我是登录页面5')
}
exports.showSign6=function(req,res){
res.send('我是登录页面6')
}
exports.showSign7=function(req,res){
res.send('我是登录页面7')
}